# RDS Postgres in the private subnets, with every credential generated by
# Terraform and stored in Secrets Manager — nothing is passed on the CLI or
# left in plaintext in the console.
#
#   image-service/dev/db-master : master credentials (JSON, managed secret)
#   image-service/dev/app       : { DATABASE_URL, JWT_SECRET, LAMBDA_API_KEY }
#
# The app secret is what the EC2 instance profile reads at boot; the Lambda
# API key is also injected into the processor function's env.

data "aws_caller_identity" "current" {}

locals {
  db_identifier = var.db_identifier
  master_secret = var.master_secret_name
  app_secret    = var.app_secret_name
  admin_user    = "image_admin"
  database_name = var.database_name
}

# ---------------- Credentials ----------------

resource "random_password" "db_master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?" # alphanumeric-friendly, safe in a URL
}

resource "random_password" "jwt_secret" {
  length  = 48
  special = false
}

resource "random_password" "lambda_api_key" {
  length  = 40
  special = false
}

resource "random_password" "admin_initial" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "db_master" {
  name                    = local.master_secret
  description             = "RDS master credentials for ${local.db_identifier} (Terraform-managed)"
  recovery_window_in_days = 0 # dev: delete without 7-day window

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({
    engine   = "postgres"
    host     = aws_db_instance.postgres.address
    port     = aws_db_instance.postgres.port
    dbname   = local.database_name
    username = local.admin_user
    password = random_password.db_master.result
    # app-convenience fields
    dbInstanceIdentifier = local.db_identifier
  })
}

resource "aws_secretsmanager_secret" "app" {
  name                    = local.app_secret
  description             = "Runtime secrets consumed by the backend container (Terraform-managed)"
  recovery_window_in_days = 0

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    DATABASE_URL     = "postgresql://${local.admin_user}:${urlencode(random_password.db_master.result)}@${aws_db_instance.postgres.address}:${aws_db_instance.postgres.port}/${local.database_name}?schema=public"
    JWT_SECRET       = random_password.jwt_secret.result
    LAMBDA_API_KEY   = random_password.lambda_api_key.result
    ADMIN_INITIAL_PW = random_password.admin_initial.result
  })
}

# ---------------- Subnet group + instance ----------------

resource "aws_db_subnet_group" "main" {
  name        = "${local.db_identifier}-subnet-group"
  description = "Private subnets for ${local.db_identifier}"
  subnet_ids  = var.private_subnet_ids

  tags = merge(var.tags, {
    Name = "${local.db_identifier}-subnet-group"
  })
}

resource "aws_db_parameter_group" "main" {
  name_prefix = "${local.db_identifier}-params-"
  family      = var.engine_version_major == 16 ? "postgres16" : "postgres${var.engine_version_major}"
  description = "Parameters for ${local.db_identifier}"

  parameter {
    name         = "rds.force_ssl"
    value        = "0" # dev: allow the container's plain TLS-off connection
    apply_method = "immediate"
  }

  tags = var.tags
}

resource "aws_db_instance" "postgres" {
  identifier            = local.db_identifier
  engine                = "postgres"
  engine_version        = var.engine_version
  instance_class        = var.instance_class
  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = local.database_name
  username = local.admin_user
  password = random_password.db_master.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [var.security_group_id]
  parameter_group_name   = aws_db_parameter_group.main.name
  port                   = var.port

  multi_az                   = false # dev
  publicly_accessible        = false # private subnets only — verified reachability is app-SG gated
  backup_window              = "03:00-03:30"
  maintenance_window         = "sun:04:00-sun:04:30"
  backup_retention_period    = var.backup_retention_days
  auto_minor_version_upgrade = true
  deletion_protection        = var.deletion_protection
  skip_final_snapshot        = !var.deletion_protection # dev env tears down cleanly
  final_snapshot_identifier  = var.deletion_protection ? "${local.db_identifier}-final" : null

  # Postgres 16 does not support IAM database auth? It does — but the app
  # connects with user/password from Secrets Manager, which is the documented
  # pattern for this project.
  copy_tags_to_snapshot = true

  tags = merge(var.tags, {
    Name = local.db_identifier
  })
}