# Image-processor Lambda: container image from ECR, triggered by S3
# ObjectCreated on uploads/ in the image bucket.
#
# Execution role is the only AWS identity it has — s3:GetObject on
# uploads/*, s3:PutObject on processed/*, CloudWatch Logs. No access keys in
# env vars; LAMBDA_API_KEY is an app-level shared secret generated by
# Terraform and stored in Secrets Manager.
#
# Creation toggle: a package_type=Image function must point at an image that
# exists. On a clean account the CI hasn't pushed yet, so apply once with
# create=false (everything else comes up), let the workflows push images,
# then flip to true and re-apply. See ../docs/DECISIONS.md.

locals {
  function_name = var.function_name
}

data "aws_partition" "current" {}
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ---------------- Execution role ----------------

data "aws_iam_policy_document" "lambda_trust" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "execution" {
  name               = "${local.function_name}-execution-role"
  description        = "Executes the image processor: S3 uploads/ read, processed/ write, logs"
  assume_role_policy = data.aws_iam_policy_document.lambda_trust.json

  tags = merge(var.tags, {
    Name = "${local.function_name}-execution-role"
  })
}

data "aws_iam_policy_document" "execution_permissions" {
  statement {
    sid    = "ReadUploadsWriteProcessed"
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:GetObjectVersion",
    ]
    resources = ["${var.bucket_arn}/uploads/*"]
  }

  statement {
    sid    = "WriteProcessed"
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:AbortMultipartUpload",
    ]
    resources = ["${var.bucket_arn}/processed/*"]
  }

  # Publishes processor events to the events queue (NOTIFY_MODE=sqs).
  statement {
    sid    = "PublishProcessorEvents"
    effect = "Allow"
    actions = [
      "sqs:SendMessage",
    ]
    resources = [var.sqs_queue_arn]
  }

  statement {
    sid    = "LambdaLogs"
    effect = "Allow"
    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
      "logs:DescribeLogStreams",
    ]
    resources = [
      "arn:${data.aws_partition.current.partition}:logs:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:log-group:${local.function_name}:log-stream:*",
    ]
  }
}

resource "aws_iam_role_policy" "execution" {
  name   = "${local.function_name}-execution-permissions"
  role   = aws_iam_role.execution.id
  policy = data.aws_iam_policy_document.execution_permissions.json
}

resource "aws_cloudwatch_log_group" "function" {
  name              = local.function_name
  retention_in_days = var.log_retention_days

  tags = var.tags
}

# ---------------- Function ----------------

resource "aws_lambda_function" "processor" {
  count = var.create ? 1 : 0

  function_name = local.function_name
  description   = "Compresses uploads/ images and reports to the backend API"

  package_type = "Image"
  image_uri    = "${var.ecr_registry}/${var.ecr_repo}:${var.image_tag}"
  image_config {
    # src/handler.handler is baked into the Dockerfile CMD; explicit here
    # so a wrong CMD in the image can't break the function.
    entry_point = ["/lambda-entrypoint.sh"]
    command     = ["src/handler.handler"]
  }

  role          = aws_iam_role.execution.arn
  memory_size   = var.memory_size
  timeout       = var.timeout_seconds
  architectures = ["x86_64"] # matches the linux/amd64 CI build

  environment {
    variables = {
      BACKEND_URL    = var.backend_base_url # unused in sqs mode; kept for the api rollback path
      LAMBDA_API_KEY = var.lambda_api_key   # unused in sqs mode; kept for the api rollback path
      NOTIFY_MODE    = "sqs"
      SQS_QUEUE_URL  = var.sqs_queue_url
      MAX_WIDTH      = "2000"
      JPEG_QUALITY   = "80"
      TARGET_BUCKET  = var.bucket_name
    }
  }

  # S3 events are delivered async; the handler reports failures itself rather
  # than throwing for object-level errors (see the repo README).
  tracing_config {
    mode = "Active"
  }

  depends_on = [
    aws_iam_role_policy.execution,
    aws_cloudwatch_log_group.function,
  ]

  tags = merge(var.tags, {
    Name = local.function_name
  })
}

# ---------------- S3 event wiring ----------------

resource "aws_lambda_permission" "s3_invoke" {
  count = var.create ? 1 : 0

  statement_id  = "AllowS3BucketNotification"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.processor[count.index].function_name
  principal     = "s3.amazonaws.com"
  source_arn    = var.bucket_arn
}

resource "aws_s3_bucket_notification" "uploads" {
  count = var.create ? 1 : 0

  bucket = var.bucket_name

  lambda_function {
    lambda_function_arn = aws_lambda_function.processor[count.index].arn
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "uploads/"
  }

  depends_on = [aws_lambda_permission.s3_invoke]
}